"""Deterministically generate a standalone Tk application from one JSON seed."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

FORMAT = "manual-tk-generator-1"
NORMAL_FORMAT = "manual-normal-case-1"
ACTION_NAMES = frozenset({"append", "clear", "backspace", "evaluate"})
OPERATOR_NAMES = {
    "add": ("ast.Add", "operator.add"),
    "subtract": ("ast.Sub", "operator.sub"),
    "multiply": ("ast.Mult", "operator.mul"),
    "true_divide": ("ast.Div", "operator.truediv"),
    "positive": ("ast.UAdd", "operator.pos"),
    "negative": ("ast.USub", "operator.neg"),
}


def canonical(value):
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def sha256(raw):
    return hashlib.sha256(raw).hexdigest()


def validate(seed):
    errors = []
    if seed.get("schema_version") == NORMAL_FORMAT:
        case = seed.get("normal_case", {})
        if not case.get("source") or len(case.get("sha256", "")) != 64:
            errors.append("normal-case")
        if not seed.get("flow"):
            errors.append("flow")
        if not seed.get("boundaries"):
            errors.append("boundaries")
        return sorted(set(errors))
    if seed.get("schema_version") != FORMAT:
        errors.append("schema-version")
    if not seed.get("application", {}).get("title"):
        errors.append("application-title")
    controls = seed.get("controls")
    if not isinstance(controls, list) or not controls:
        errors.append("controls")
        controls = []
    if any(control.get("action") not in ACTION_NAMES for control in controls):
        errors.append("control-action")
    positions = [(control.get("row"), control.get("column")) for control in controls]
    if len(positions) != len(set(positions)):
        errors.append("control-position")
    expression = seed.get("expression", {})
    selected = {
        *expression.get("binary_operators", {}).values(),
        *expression.get("unary_operators", {}).values(),
    }
    if not selected or not selected.issubset(OPERATOR_NAMES):
        errors.append("expression-operators")
    if not isinstance(expression.get("maximum_characters"), int):
        errors.append("maximum-characters")
    return sorted(set(errors))


def operator_lines(seed, section):
    selected = seed["expression"][section]
    return [
        f"    {OPERATOR_NAMES[name][0]}: {OPERATOR_NAMES[name][1]},"
        for _, name in sorted(selected.items())
    ]


def control_lines(seed):
    theme = seed["theme"]
    lines = []
    for control in seed["controls"]:
        lines.extend(
            (
                "    Button(",
                f"        root, text={control['label']!r},",
                f"        fg={theme['button_foreground']!r},",
                f"        bg={theme['button_background']!r},",
                "        command=lambda action="
                f"{control['action']!r}, value={control['value']!r}: dispatch(action, value),",
                "        height=1, width=7,",
                f"    ).grid(row={control['row']}, column={control['column']})",
            )
        )
    return lines


def render(seed):
    application = seed["application"]
    theme = seed["theme"]
    display = seed["display"]
    lines = [
        '"""Generated from seed.json. Do not edit this file by hand."""',
        "",
        "import ast",
        "import operator",
        "import sys",
        "from tkinter import Button, Entry, StringVar, Tk",
        "",
        f"MAXIMUM_CHARACTERS = {seed['expression']['maximum_characters']}",
        "BINARY_OPERATORS = {",
        *operator_lines(seed, "binary_operators"),
        "}",
        "UNARY_OPERATORS = {",
        *operator_lines(seed, "unary_operators"),
        "}",
        'ERRORS = {"ZeroDivisionError": "division-by-zero"}',
        'state = {"expression": ""}',
        "display = None",
        "",
        "",
        "def evaluate_node(node):",
        "    if isinstance(node, ast.Expression):",
        "        return evaluate_node(node.body)",
        "    if isinstance(node, ast.Constant) and type(node.value) in (int, float):",
        "        return node.value",
        "    if isinstance(node, ast.BinOp) and type(node.op) in BINARY_OPERATORS:",
        "        return BINARY_OPERATORS[type(node.op)](",
        "            evaluate_node(node.left), evaluate_node(node.right)",
        "        )",
        "    if isinstance(node, ast.UnaryOp) and type(node.op) in UNARY_OPERATORS:",
        "        return UNARY_OPERATORS[type(node.op)](evaluate_node(node.operand))",
        '    raise ValueError("invalid-expression")',
        "",
        "",
        "def evaluate_expression(expression):",
        "    if not expression or len(expression) > MAXIMUM_CHARACTERS:",
        '        raise ValueError("invalid-expression")',
        "    return evaluate_node(ast.parse(expression, mode='eval'))",
        "",
        "",
        "def present(value):",
        "    return str(int(value)) if isinstance(value, float) and value.is_integer() else str(value)",
        "",
        "",
        "def append(value):",
        '    state["expression"] = (state["expression"] + value)[:MAXIMUM_CHARACTERS]',
        '    display.set(state["expression"])',
        "",
        "",
        "def clear(_value):",
        '    state["expression"] = ""',
        '    display.set("")',
        "",
        "",
        "def backspace(_value):",
        '    state["expression"] = state["expression"][:-1]',
        '    display.set(state["expression"])',
        "",
        "",
        "def evaluate(_value):",
        "    try:",
        '        result = present(evaluate_expression(state["expression"]))',
        "    except (ArithmeticError, SyntaxError, ValueError) as error:",
        '        result = ERRORS.get(type(error).__name__, "invalid-expression")',
        '    state["expression"] = result',
        "    display.set(result)",
        "",
        "",
        'ROUTES = {"append": append, "clear": clear, "backspace": backspace, "evaluate": evaluate}',
        "",
        "",
        "def dispatch(action, value):",
        "    ROUTES[action](value)",
        "",
        "",
        "def launch():",
        "    global display",
        "    root = Tk()",
        f"    root.configure(bg={theme['background']!r})",
        f"    root.title({application['title']!r})",
        f"    root.geometry({application['geometry']!r})",
        "    display = StringVar()",
        "    Entry(root, textvariable=display).grid(",
        f"        row={display['row']}, column={display['column']},",
        f"        columnspan={display['column_span']}, ipadx={display['ipadx']},",
        "    )",
        *control_lines(seed),
        "    root.mainloop()",
        "",
        "",
        "def main(argv=None):",
        "    arguments = list(sys.argv if argv is None else argv)",
        '    if len(arguments) == 3 and arguments[1] == "--evaluate":',
        "        try:",
        "            print(present(evaluate_expression(arguments[2])))",
        "            return 0",
        "        except ZeroDivisionError:",
        '            print("division-by-zero")',
        "            return 1",
        "        except (SyntaxError, ValueError):",
        '            print("invalid-expression")',
        "            return 1",
        "    launch()",
        "    return 0",
        "",
        "",
        'if __name__ == "__main__":',
        "    raise SystemExit(main())",
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def verify(seed, application_path):
    results = []
    for case in seed["acceptance"]:
        completed = subprocess.run(
            [sys.executable, str(application_path), "--evaluate", case["expression"]],
            check=False,
            capture_output=True,
            text=True,
        )
        actual = completed.stdout.strip()
        expected = case.get("result", case.get("error"))
        expected_exit = 0 if "result" in case else 1
        results.append(actual == expected and completed.returncode == expected_exit)
    if not all(results):
        raise ValueError("acceptance-failed")
    return {"passed": sum(results), "total": len(results)}


def generate(seed_path, output):
    seed_path = Path(seed_path).resolve(strict=True)
    output = Path(output).resolve(strict=False)
    seed = json.loads(seed_path.read_text(encoding="utf-8"))
    errors = validate(seed)
    if errors:
        raise ValueError(",".join(errors))
    normal = seed.get("schema_version") == NORMAL_FORMAT
    if normal:
        source_path = seed_path.parent / seed["normal_case"]["source"]
        source = source_path.read_bytes()
        if sha256(source) != seed["normal_case"]["sha256"]:
            raise ValueError("normal-case-hash-mismatch")
    else:
        source = render(seed)
    manifest = {
        "format": seed["schema_version"],
        "seed_sha256": sha256(canonical(seed)),
        "files": {"main.py": sha256(source)},
    }
    stage = Path(tempfile.mkdtemp(prefix="." + output.name + "-", dir=output.parent))
    try:
        (stage / "main.py").write_bytes(source)
        evidence = (
            {
                "normal_case_byte_identical": source
                == (seed_path.parent / seed["normal_case"]["source"]).read_bytes(),
                "passed": 1,
                "total": 1,
            }
            if normal
            else verify(seed, stage / "main.py")
        )
        manifest["verification"] = evidence
        (stage / "manifest.json").write_bytes(canonical(manifest))
        backup = output.with_name("." + output.name + ".previous")
        if backup.exists():
            shutil.rmtree(backup)
        if output.exists():
            output.rename(backup)
        stage.rename(output)
        if backup.exists():
            shutil.rmtree(backup)
    except BaseException:
        shutil.rmtree(stage, ignore_errors=True)
        raise
    return manifest


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("seed")
    parser.add_argument("--output", default="generated")
    arguments = parser.parse_args(argv)
    result = generate(arguments.seed, arguments.output)
    sys.stdout.buffer.write(canonical(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
